source :rubygems

gem 'rails', '~> 2.3.8'
gem 'sqlite3-ruby', '~> 1.3.1'

gem 'sunspot', :path => File.expand_path('../../../../sunspot', __FILE__)
gem 'sunspot_rails', :path => File.expand_path('../../..', __FILE__)

group :test do
	gem 'rspec-rails', '~> 1.3.0'

	if RUBY_VERSION.to_f >= 1.9
    gem 'ruby-debug19', :require => nil
    gem 'test-unit', '1.2.3'
  else
    gem 'ruby-debug', :require => nil
  end
end
