source :rubygems

gem 'rails', '= 2.3.4'
gem 'sunspot', :path => File.expand_path('../../../../sunspot', __FILE__)
gem 'sunspot_rails', :path => File.expand_path('../../..', __FILE__)
gem 'sqlite3-ruby', '~> 1.3.1'
group :test do
	gem 'rspec-rails', '~> 1.3.0'
	gem 'ruby-debug', :require => nil
end
