source :rubygems

gem 'rails', '~> 2.3.4'
gem 'sunspot', :path => File.expand_path('../../sunspot', __FILE__)
gem 'sunspot_rails', :path => File.expand_path('..', __FILE__), :require => 'sunspot/rails'
gem 'sqlite3-ruby', '~> 1.3.1'
group :test do
	gem 'rspec', '~> 1.3'
	gem 'rspec-rails', '~> 1.3'
end
