source "http://rubygems.org"

gem 'sunspot_solr', :path => File.expand_path('../../sunspot_solr', __FILE__)

gemspec

group :development do
  gem 'rake', '~> 10.5'
end

gem 'rsolr', ENV['RSOLR'] if ENV['RSOLR']
