source "http://rubygems.org"

gem 'sunspot_solr', :path => File.expand_path('../../sunspot_solr', __FILE__)

gemspec

group :development do
  gem 'rake'
  gem 'rdoc', '>= 2.4.2' # for RDoc::Task on Travis CI
end
