ENV['RUBYOPT'] = '-W1'

# encoding: UTF-8

require 'rspec/core/rake_task'

Dir['tasks/**/*.rake'].each { |t| load t }

desc "Run all examples"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = '--format documentation'
end

task :default => :spec
